menu:
  Home: /
  Info: /Info
  Archives: /archives

footer:
  Datenschutzerklärung: /Datenschutz
  Impressum: /Impressum
  
# gitment
gitment: false
gitment_owner:
gitment_repo:
gitment_client_id:
gitment_client_secret:

# valine comment
valine: false
leancloud_id: 
leancloud_key: 

# disqus comment
disqus: false
disqus_shortname:

# google analytics
googleTrackId:
