menu:
  Home: /
  Info: /Information/index.html
  Archiv: /Archiv/index.html
  ➚ Instagram: https://instagram.com/tomjkn
  ➚ Facebook: https://www.facebook.com/thmsjkn
  ➚ Flickr: https://www.flickr.com/people/bonalumo/

footer:
  Datenschutzerklärung: /Datenschutz/index.html
  Impressum: /Impressum/index.html
  
# gitment
gitment: false
gitment_owner:
gitment_repo:
gitment_client_id:
gitment_client_secret:

# valine comment
valine: false
leancloud_id: 
leancloud_key: 

# disqus comment
disqus: false
disqus_shortname:

# google analytics
googleTrackId:
